// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | PopVideoSlice
  | VideoSlice
  | PopButtonSlice
  | PopHeadlineSlice
  | HeadlineSlice
  | PopTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Headline → Default → Primary*
 */
export interface HeadlineSliceDefaultPrimary {
  /**
   * Headline field in *Headline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Sub headline field in *Headline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline.default.primary.sub_headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headline: prismic.RichTextField;

  /**
   * Alignment field in *Headline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: headline.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  alignment: prismic.SelectField<"left" | "center", "filled">;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Headline*
 */
type HeadlineSliceVariation = HeadlineSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `headline`
 * - **Description**: Headline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSlice = prismic.SharedSlice<
  "headline",
  HeadlineSliceVariation
>;

/**
 * Primary content in *PopButton → Default → Primary*
 */
export interface PopButtonSliceDefaultPrimary {
  /**
   * Button field in *PopButton → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_button.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for PopButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopButton*
 */
type PopButtonSliceVariation = PopButtonSliceDefault;

/**
 * PopButton Shared Slice
 *
 * - **API ID**: `pop_button`
 * - **Description**: PopButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopButtonSlice = prismic.SharedSlice<
  "pop_button",
  PopButtonSliceVariation
>;

/**
 * Primary content in *PopHeadline → Default → Primary*
 */
export interface PopHeadlineSliceDefaultPrimary {
  /**
   * Headline field in *PopHeadline → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_headline.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;
}

/**
 * Default variation for PopHeadline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopHeadlineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopHeadlineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopHeadline*
 */
type PopHeadlineSliceVariation = PopHeadlineSliceDefault;

/**
 * PopHeadline Shared Slice
 *
 * - **API ID**: `pop_headline`
 * - **Description**: PopHeadline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopHeadlineSlice = prismic.SharedSlice<
  "pop_headline",
  PopHeadlineSliceVariation
>;

/**
 * Item in *PopText → Default → Primary → Items*
 */
export interface PopTextSliceDefaultPrimaryItemsItem {
  /**
   * Styling field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1-column
   * - **API ID Path**: pop_text.default.primary.items[].styling
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  styling: prismic.SelectField<
    "1-column" | "2-columns" | "2-columns-reversed" | "image-2-columns",
    "filled"
  >;

  /**
   * Headline field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Rich Text field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField;

  /**
   * Image field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *PopText → Default → Primary*
 */
export interface PopTextSliceDefaultPrimary {
  /**
   * Button Text field in *PopText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Headline field in *PopText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Items field in *PopText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<PopTextSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for PopText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopText*
 */
type PopTextSliceVariation = PopTextSliceDefault;

/**
 * PopText Shared Slice
 *
 * - **API ID**: `pop_text`
 * - **Description**: PopText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopTextSlice = prismic.SharedSlice<
  "pop_text",
  PopTextSliceVariation
>;

/**
 * Primary content in *PopVideo → Default → Primary*
 */
export interface PopVideoSliceDefaultPrimary {
  /**
   * Poster field in *PopVideo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_video.default.primary.poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;

  /**
   * Video Url field in *PopVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_video.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;
}

/**
 * Default variation for PopVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopVideo*
 */
type PopVideoSliceVariation = PopVideoSliceDefault;

/**
 * PopVideo Shared Slice
 *
 * - **API ID**: `pop_video`
 * - **Description**: PopVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopVideoSlice = prismic.SharedSlice<
  "pop_video",
  PopVideoSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Poster field in *Video → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;

  /**
   * Video Url field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeadlineSlice,
      HeadlineSliceDefaultPrimary,
      HeadlineSliceVariation,
      HeadlineSliceDefault,
      PopButtonSlice,
      PopButtonSliceDefaultPrimary,
      PopButtonSliceVariation,
      PopButtonSliceDefault,
      PopHeadlineSlice,
      PopHeadlineSliceDefaultPrimary,
      PopHeadlineSliceVariation,
      PopHeadlineSliceDefault,
      PopTextSlice,
      PopTextSliceDefaultPrimaryItemsItem,
      PopTextSliceDefaultPrimary,
      PopTextSliceVariation,
      PopTextSliceDefault,
      PopVideoSlice,
      PopVideoSliceDefaultPrimary,
      PopVideoSliceVariation,
      PopVideoSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
