// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Settings → Socials*
 */
export interface HeaderDocumentDataSocialsItem {
  /**
   * Icon field in *Settings → Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.socials[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * CTA field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Navigation Header field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_header: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Navigation Footer field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation_footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_footer: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<HeaderDocumentDataSocialsItem>>;

  /**
   * Footer Bottom Line field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.footer_bottom_line
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_bottom_line: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CardsSlice
  | AboutUsSlice
  | SpaceSlice
  | TeamAdvancedSlice
  | TeamSlice
  | SliderSlice
  | GridSlice
  | PopVideoSlice
  | VideoSlice
  | PopButtonSlice
  | PopHeadlineSlice
  | HeadlineSlice
  | PopTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HeaderDocument | PageDocument;

/**
 * Item in *AboutUs → Default → Primary → Items*
 */
export interface AboutUsSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *AboutUs → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Url field in *AboutUs → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.items[].video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;

  /**
   * Headline field in *AboutUs → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Richtext field in *AboutUs → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.items[].richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField;

  /**
   * Category field in *AboutUs → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Why
   * - **API ID Path**: about_us.default.primary.items[].category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"Why" | "What" | "How" | "Who", "filled">;
}

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * Items field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<AboutUsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>;

/**
 * Item in *Cards → Default → Primary → Items*
 */
export interface CardsSliceDefaultPrimaryItemsItem {
  /**
   * Headline field in *Cards → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Text field in *Cards → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * Items field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Primary content in *Grid → Default → Primary*
 */
export interface GridSliceDefaultPrimary {
  /**
   * Text Problem field in *Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.text_problem
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_problem: prismic.KeyTextField;

  /**
   * Text Solution field in *Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.default.primary.text_solution
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_solution: prismic.KeyTextField;
}

/**
 * Default variation for Grid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Grid*
 */
type GridSliceVariation = GridSliceDefault;

/**
 * Grid Shared Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Grid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSlice = prismic.SharedSlice<"grid", GridSliceVariation>;

/**
 * Primary content in *Headline → Default → Primary*
 */
export interface HeadlineSliceDefaultPrimary {
  /**
   * Headline field in *Headline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Sub headline field in *Headline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline.default.primary.sub_headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_headline: prismic.RichTextField;

  /**
   * Alignment field in *Headline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: headline.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  alignment: prismic.SelectField<"left" | "center", "filled">;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Headline*
 */
type HeadlineSliceVariation = HeadlineSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `headline`
 * - **Description**: Headline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSlice = prismic.SharedSlice<
  "headline",
  HeadlineSliceVariation
>;

/**
 * Primary content in *PopButton → Default → Primary*
 */
export interface PopButtonSliceDefaultPrimary {
  /**
   * Button field in *PopButton → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_button.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for PopButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopButton*
 */
type PopButtonSliceVariation = PopButtonSliceDefault;

/**
 * PopButton Shared Slice
 *
 * - **API ID**: `pop_button`
 * - **Description**: PopButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopButtonSlice = prismic.SharedSlice<
  "pop_button",
  PopButtonSliceVariation
>;

/**
 * Primary content in *PopHeadline → Default → Primary*
 */
export interface PopHeadlineSliceDefaultPrimary {
  /**
   * Headline field in *PopHeadline → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_headline.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;
}

/**
 * Default variation for PopHeadline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopHeadlineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopHeadlineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopHeadline*
 */
type PopHeadlineSliceVariation = PopHeadlineSliceDefault;

/**
 * PopHeadline Shared Slice
 *
 * - **API ID**: `pop_headline`
 * - **Description**: PopHeadline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopHeadlineSlice = prismic.SharedSlice<
  "pop_headline",
  PopHeadlineSliceVariation
>;

/**
 * Item in *PopText → Default → Primary → Items*
 */
export interface PopTextSliceDefaultPrimaryItemsItem {
  /**
   * Styling field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1-column
   * - **API ID Path**: pop_text.default.primary.items[].styling
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  styling: prismic.SelectField<
    | "1-column"
    | "image-2-columns"
    | "2-columns"
    | "2-columns-reversed"
    | "2-columns-big-image"
    | "2-columns-big-image-reversed",
    "filled"
  >;

  /**
   * Headline field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Rich Text field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField;

  /**
   * Rich Text 2 field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This is only used when styling is set to: image-2-columns
   * - **API ID Path**: pop_text.default.primary.items[].rich_text_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text_2: prismic.RichTextField;

  /**
   * Image field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button field in *PopText → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *PopText → Default → Primary*
 */
export interface PopTextSliceDefaultPrimary {
  /**
   * Headline field in *PopText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Closed field in *PopText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: pop_text.default.primary.closed
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  closed: prismic.BooleanField;

  /**
   * Items field in *PopText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_text.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<PopTextSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for PopText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopText*
 */
type PopTextSliceVariation = PopTextSliceDefault;

/**
 * PopText Shared Slice
 *
 * - **API ID**: `pop_text`
 * - **Description**: PopText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopTextSlice = prismic.SharedSlice<
  "pop_text",
  PopTextSliceVariation
>;

/**
 * Primary content in *PopVideo → Default → Primary*
 */
export interface PopVideoSliceDefaultPrimary {
  /**
   * Poster field in *PopVideo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_video.default.primary.poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;

  /**
   * Video Url field in *PopVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pop_video.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;
}

/**
 * Default variation for PopVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopVideo*
 */
type PopVideoSliceVariation = PopVideoSliceDefault;

/**
 * PopVideo Shared Slice
 *
 * - **API ID**: `pop_video`
 * - **Description**: PopVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopVideoSlice = prismic.SharedSlice<
  "pop_video",
  PopVideoSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → Items*
 */
export interface SliderSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *Slider → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Items field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<SliderSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Primary content in *Space → Default → Primary*
 */
export interface SpaceSliceDefaultPrimary {
  /**
   * Height field in *Space → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: space.default.primary.height
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height: prismic.SelectField<"xs" | "s" | "m" | "lg" | "xl" | "2xl">;
}

/**
 * Default variation for Space Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpaceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpaceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Space*
 */
type SpaceSliceVariation = SpaceSliceDefault;

/**
 * Space Shared Slice
 *
 * - **API ID**: `space`
 * - **Description**: Space
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpaceSlice = prismic.SharedSlice<"space", SpaceSliceVariation>;

/**
 * Item in *Team → Default → Primary → Items*
 */
export interface TeamSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Url field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;

  /**
   * Headline field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Richtext field in *Team → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[].richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Items field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *TeamAdvanced → Default → Primary → Items*
 */
export interface TeamAdvancedSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *TeamAdvanced → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_advanced.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Url field in *TeamAdvanced → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_advanced.default.primary.items[].video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;

  /**
   * Headline field in *TeamAdvanced → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_advanced.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Richtext field in *TeamAdvanced → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_advanced.default.primary.items[].richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField;
}

/**
 * Primary content in *TeamAdvanced → Default → Primary*
 */
export interface TeamAdvancedSliceDefaultPrimary {
  /**
   * Items field in *TeamAdvanced → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_advanced.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<TeamAdvancedSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for TeamAdvanced Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamAdvancedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamAdvancedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamAdvanced*
 */
type TeamAdvancedSliceVariation = TeamAdvancedSliceDefault;

/**
 * TeamAdvanced Shared Slice
 *
 * - **API ID**: `team_advanced`
 * - **Description**: TeamAdvanced
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamAdvancedSlice = prismic.SharedSlice<
  "team_advanced",
  TeamAdvancedSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Poster field in *Video → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;

  /**
   * Video Url field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSocialsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimaryItemsItem,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      CardsSlice,
      CardsSliceDefaultPrimaryItemsItem,
      CardsSliceDefaultPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      GridSlice,
      GridSliceDefaultPrimary,
      GridSliceVariation,
      GridSliceDefault,
      HeadlineSlice,
      HeadlineSliceDefaultPrimary,
      HeadlineSliceVariation,
      HeadlineSliceDefault,
      PopButtonSlice,
      PopButtonSliceDefaultPrimary,
      PopButtonSliceVariation,
      PopButtonSliceDefault,
      PopHeadlineSlice,
      PopHeadlineSliceDefaultPrimary,
      PopHeadlineSliceVariation,
      PopHeadlineSliceDefault,
      PopTextSlice,
      PopTextSliceDefaultPrimaryItemsItem,
      PopTextSliceDefaultPrimary,
      PopTextSliceVariation,
      PopTextSliceDefault,
      PopVideoSlice,
      PopVideoSliceDefaultPrimary,
      PopVideoSliceVariation,
      PopVideoSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimaryItemsItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
      SpaceSlice,
      SpaceSliceDefaultPrimary,
      SpaceSliceVariation,
      SpaceSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryItemsItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TeamAdvancedSlice,
      TeamAdvancedSliceDefaultPrimaryItemsItem,
      TeamAdvancedSliceDefaultPrimary,
      TeamAdvancedSliceVariation,
      TeamAdvancedSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
