// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  headline: dynamic(() => import("./Headline")),
  pop_button: dynamic(() => import("./PopButton")),
  pop_headline: dynamic(() => import("./PopHeadline")),
  pop_text: dynamic(() => import("./PopContent")),
};
