// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  cards: dynamic(() => import("./Cards")),
  grid: dynamic(() => import("./Grid")),
  headline: dynamic(() => import("./Headline")),
  pop_button: dynamic(() => import("./PopButton")),
  pop_headline: dynamic(() => import("./PopHeadline")),
  pop_text: dynamic(() => import("./PopText")),
  pop_video: dynamic(() => import("./PopVideo")),
  slider: dynamic(() => import("./Slider")),
  small_text: dynamic(() => import("./SmallText")),
  space: dynamic(() => import("./Space")),
  team: dynamic(() => import("./Team")),
  team_advanced: dynamic(() => import("./TeamAdvanced")),
  video: dynamic(() => import("./Video")),
};
